//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPad.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevPad.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new tab.
        /// </summary>
        internal static string AddButtonTooltip {
            get {
                return ResourceManager.GetString("AddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new tab group.
        /// </summary>
        internal static string AddGroupButtonTooltip {
            get {
                return ResourceManager.GetString("AddGroupButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |All Files (*.*)|*.*.
        /// </summary>
        internal static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |All Known Files|{0}.
        /// </summary>
        internal static string AllKnownFilesFilter {
            get {
                return ResourceManager.GetString("AllKnownFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Save Period (sec).
        /// </summary>
        internal static string AutoSavePeriodDisplayName {
            get {
                return ResourceManager.GetString("AutoSavePeriodDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove deleted files from this list.
        /// </summary>
        internal static string CleanRecentList {
            get {
                return ResourceManager.GetString("CleanRecentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear this list.
        /// </summary>
        internal static string ClearRecentList {
            get {
                return ResourceManager.GetString("ClearRecentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab group.
        /// </summary>
        internal static string CloseTabGroupTooltip {
            get {
                return ResourceManager.GetString("CloseTabGroupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab.
        /// </summary>
        internal static string CloseTabTooltip {
            get {
                return ResourceManager.GetString("CloseTabTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid color.
        /// </summary>
        internal static string ColorError {
            get {
                return ResourceManager.GetString("ColorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; has been changed by another program, do you want to reload it?.
        /// </summary>
        internal static string ConfirmChanged {
            get {
                return ResourceManager.GetString("ConfirmChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; has been deleted by another program, do you want to close it?.
        /// </summary>
        internal static string ConfirmDeleted {
            get {
                return ResourceManager.GetString("ConfirmDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes to the {0} document, are you sure you want to discard them?.
        /// </summary>
        internal static string ConfirmDiscardDocument {
            get {
                return ResourceManager.GetString("ConfirmDiscardDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes to the {0} documents, are you sure you want to discard them?.
        /// </summary>
        internal static string ConfirmDiscardDocuments {
            get {
                return ResourceManager.GetString("ConfirmDiscardDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; has been changed by another program and has been modified here, do you want to reload it?.
        /// </summary>
        internal static string ConfirmModifiedChanged {
            get {
                return ResourceManager.GetString("ConfirmModifiedChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; has been deleted by another program and has been modified here, do you want to close it?.
        /// </summary>
        internal static string ConfirmModifiedDeleted {
            get {
                return ResourceManager.GetString("ConfirmModifiedDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file wasn&apos;t saved because of an unauthorized access error. Do you want to restart DevPad as Administrator?.
        /// </summary>
        internal static string ConfirmRestartAsAdmin {
            get {
                return ResourceManager.GetString("ConfirmRestartAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultGroupName {
            get {
                return ResourceManager.GetString("DefaultGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop {0}.
        /// </summary>
        internal static string DesktopIndexedName {
            get {
                return ResourceManager.GetString("DesktopIndexedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DevPadIcon {
            get {
                object obj = ResourceManager.GetObject("DevPadIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Details.
        /// </summary>
        internal static string ErrorDetails {
            get {
                return ResourceManager.GetString("ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to get the text from the editor..
        /// </summary>
        internal static string ErrorGetText {
            get {
                return ResourceManager.GetString("ErrorGetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Details.
        /// </summary>
        internal static string HideDetails {
            get {
                return ResourceManager.GetString("HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty or whitespace.
        /// </summary>
        internal static string NameError {
            get {
                return ResourceManager.GetString("NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Files ({1})|{1}.
        /// </summary>
        internal static string OneFileFilter {
            get {
                return ResourceManager.GetString("OneFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevPad only supports 64-bit versions of Windows..
        /// </summary>
        internal static string Only64BitWindows {
            get {
                return ResourceManager.GetString("Only64BitWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin tab.
        /// </summary>
        internal static string PinTabTooltip {
            get {
                return ResourceManager.GetString("PinTabTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is reserved.
        /// </summary>
        internal static string ReservedNameError {
            get {
                return ResourceManager.GetString("ReservedNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running on &apos;{0}&apos;.
        /// </summary>
        internal static string RunningOnDeskop {
            get {
                return ResourceManager.GetString("RunningOnDeskop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        internal static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        internal static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln: {0} Ch: {1}.
        /// </summary>
        internal static string StatusPosition {
            get {
                return ResourceManager.GetString("StatusPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection: {0}.
        /// </summary>
        internal static string StatusSelection {
            get {
                return ResourceManager.GetString("StatusSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Info.
        /// </summary>
        internal static string SystemInfo {
            get {
                return ResourceManager.GetString("SystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred..
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin tab.
        /// </summary>
        internal static string UnpinTabTooltip {
            get {
                return ResourceManager.GetString("UnpinTabTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Untitled {0}).
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;A HREF=&quot;https://go.microsoft.com/fwlink/p/?LinkId=2124703&quot;&gt;Click here to download the WebView2 Runtime.&lt;/A&gt;.
        /// </summary>
        internal static string WebViewDownload {
            get {
                return ResourceManager.GetString("WebViewDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to initialize the WebView..
        /// </summary>
        internal static string WebViewError {
            get {
                return ResourceManager.GetString("WebViewError", resourceCulture);
            }
        }
    }
}
